name: Ziti Webhook Action - Python
description: POST the GitHub webhook payload over a Ziti network
branding:
  icon: zap
  color: red
inputs:
  zitiId:
    description: Identity JSON for an enrolled Ziti endpoint
    required: true
  webhookUrl:
    description: Ziti URL for posting the payload
    required: true
  eventJson:
    description: GitHub event JSON (github.event)
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
